export const GET_FORUMS_LOADING = "GET_FORUMS_LOADING";
export const GET_FORUMS_ERROR = "GET_FORUMS_ERROR";
export const GET_FORUMS_SUCCESS = "GET_FORUMS_SUCCESS";

export const POST_FORUM_LOADING = "POST_FORUM_LOADING";
export const POST_FORUM_ERROR = "POST_FORUM_ERROR";
export const POST_FORUM_SUCCESS = "POST_FORUM_SUCCESS";

export const PATCH_FORUM_LOADING = "PATCH_FORUM_LOADING";
export const PATCH_FORUM_ERROR = "PATCH_FORUM_ERROR";
export const PATCH_FORUM_SUCCESS = "PATCH_FORUM_SUCCESS";

export const DELETE_FORUM_LOADING = "DELETE_FORUM_LOADING";
export const DELETE_FORUM_ERROR = "DELETE_FORUM_ERROR";
export const DELETE_FORUM_SUCCESS = "DELETE_FORUM_SUCCESS";

export const SET_CURRENT='SET_CURRENT';