export const GET_USERS_LOADING = "GET_USERS_LOADING";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const POST_SIGNUP_LOADING = "POST_SIGNUP_LOADING";
export const POST_SIGNUP_ERROR = "POST_SIGNUP_ERROR";
export const POST_SIGNUP_SUCCESS = "POST_SIGNUP_SUCCESS";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const RESET = "RESET";
